apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pyae-c7-capstone-eks
  region: us-east-1
  version: "1.27"

managedNodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 5
    volumeSize: 80
    taints:
      - key: "dedicated"
        value: "upg"
        effect: "NoSchedule"
