---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: { { .Release.Name } }
    meta.helm.sh/release-namespace: { { .Release.Name } }
  name: { { .Values.redis.name } }
  namespace: { { .Values.namespace } }
  labels:
    app: { { .Values.redis.name } }
spec:
  ports:
    - port: { { .Values.redis.port } }
      name: { { .Values.redis.name } }
  clusterIP: None
  selector:
    app: { { .Values.redis.name } }
